version: '3.1'
services:
  web:
    image: "xwiki:mysql-tomcat"
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwikidb
      - DB_DATABASE=xwiki
    volumes:
      - ./xwikidata:/usr/local/xwiki
  xwikidb:
    image: "mysql:5.7"
    volumes:
      - ./xwiki.cnf:/etc/mysql/conf.d/xwiki.cnf
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
 