version: '3.4'
networks:
    webnet:
        driver: bridge
services:
    webapp:
        build: .
        image: qijunbo/jdk:8
        ports:
            - 8090:80
        restart: always
        environment:
            JAVA_OPTS: -server -Xms256m -Xmx1024m -XX:MaxPermSize=256m -Duser.timezone=Asia/Shanghai
        volumes:
            - ./bin:/init.d
           # - ./app.jar:/app/webapp.jar
        networks:
            - webnet

