version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
#      - /docker/everyone/initsql:/docker-entrypoint-initdb.d
      - /docker/everyone/conf/docker.cnf:/etc/my.cnf
    ports:
      - "3336:3306"
    networks:
      - webnet   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sunway123#
#      MYSQL_DATABASE: dbs_lims_elab
      MYSQL_USER: dbs_lims_elab
      MYSQL_PASSWORD: dbs_lims_elab
    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      test: ["CMD", "mysqlcheck", "--check", "--databases", "dbs_lims_elab", "-udbs_lims_elab", "-pdbs_lims_elab"] 
      interval: 20s
      timeout: 2s
      retries: 5
      start_period: 6m50s
  redis:
    image: redis:alpine
    volumes:
      - /docker/everyone/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - webnet
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always 
  web:
    depends_on:
      - db
  #  image: registry.cn-hangzhou.aliyuncs.com/qijunbo/lims:1.0.1
    image: sunway/lims:elab-2018.08.23
    volumes:
      - ./logs:/usr/local/tomcat/logs
      - ./appLog:/appLog
    ports:
      - "8100:8080"
    networks:
      - webnet
    restart: always
    environment:
      CONTEXTPATH: lims
      RESOURCE_NAME: framework
      APP_DB_HOST: db
      APP_DB_PORT: 3306
      APP_DB_USER: dbs_lims_elab
      APP_DB_PASSWORD: dbs_lims_elab
      APP_DATABASE: dbs_lims_elab
volumes:
  db_data:
networks:
  webnet:
