version: "3.4"
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - /docker/everyone/initsql:/docker-entrypoint-initdb.d
      - /docker/everyone/conf/docker.cnf:/etc/my.cnf
    networks:
      - webnet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sunway123#
      MYSQL_DATABASE: dbs_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: sunway123#
  web:
    depends_on:
      - db
    image: qijunbo/swagger_demo:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
      restart_policy:
        condition: on-failure
    ports:
      - "32794:80"
    networks:
      - webnet
networks:
  webnet:
volumes:
  db_data:
