version: '3.4'
networks:
  webnet:
    driver: bridge
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - /opt/limsst/mysql/data:/var/lib/mysql
      - ./config/mysql/initsql/:/docker-entrypoint-initdb.d
      - ./docker.cnf:/etc/my.cnf
    networks:
      - webnet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: product
      MYSQL_USER: product
      MYSQL_PASSWORD: sunway123#
  adminer:
    image: phpmyadmin/phpmyadmin
#    image: adminer:4.6
    restart: always
    environment:
      PMA_HOST: 192.168.47.129
    ports:
      - 8822:80


 
