version: '3.4'
networks:
  webnet:
    driver: bridge
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker.cnf:/etc/my.cnf
    networks:
      - webnet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: deeplove
      MYSQL_DATABASE: product
      MYSQL_USER: product
      MYSQL_PASSWORD: sunway123#
  adminer:
    image: phpmyadmin/phpmyadmin
#    image: adminer:4.6
    restart: always
    environment:
      PMA_HOST: 172.19.58.226
    ports:
      - 8822:80


 
